import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from database import get_connection


def generate_pdf_report(subject):
    """
    Generate Subject-wise Attendance PDF Report.
    Returns generated PDF path.
    """

    conn = get_connection()
    cursor = conn.cursor()

    # Attendance records for selected subject
    cursor.execute("""
        SELECT
            student_name,
            date,
            time,
            status
        FROM attendance
        WHERE subject = ?
        ORDER BY date, time
    """, (subject,))

    records = cursor.fetchall()

    # Total registered students
    cursor.execute("""
        SELECT COUNT(*)
        FROM students
    """)

    total_students = cursor.fetchone()[0]

    attendance_records = len(records)

    conn.close()

    # Create reports folder
    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    filename = f"reports/Attendance_{subject}_{timestamp}.pdf"

    doc = SimpleDocTemplate(filename, pagesize=letter)

    styles = getSampleStyleSheet()

    elements = []

    # ==========================
    # HEADER
    # ==========================

    elements.append(
        Paragraph(
            "<font size='22'><b>FACREC</b></font>",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "<b>Face Recognition Attendance System</b>",
            styles["Heading2"]
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(f"<b>Subject :</b> {subject}", styles["Normal"])
    )

    elements.append(
        Paragraph(
            f"<b>Generated :</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # SUMMARY
    # ==========================

    elements.append(
        Paragraph(
            "<b>Attendance Summary</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Total Registered Students :</b> {total_students}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Attendance Records ({subject}) :</b> {attendance_records}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # NO RECORDS
    # ==========================

    if attendance_records == 0:

        elements.append(
            Paragraph(
                "<font color='red'><b>No attendance records found for this subject.</b></font>",
                styles["Normal"]
            )
        )

        elements.append(Spacer(1, 20))

        elements.append(
            Paragraph(
                "<b>Generated by FACREC v1.0</b>",
                styles["Normal"]
            )
        )

        doc.build(elements)

        return filename

    # ==========================
    # TABLE
    # ==========================

    table_data = [
        ["Student", "Date", "Time", "Status"]
    ]

    for row in records:
        table_data.append(list(row))

    table = Table(table_data)

    table.setStyle(TableStyle([

        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),

        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),

    ]))

    elements.append(table)

    elements.append(Spacer(1, 30))

    # ==========================
    # FOOTER
    # ==========================

    elements.append(
        Paragraph(
            "<b>Generated by FACREC v1.0</b>",
            styles["Normal"]
        )
    )

    doc.build(elements)

    return filename